source 'https://gems.ruby-china.org/'
#source 'https://rubygems.org'
#source 'http://soundwave.ivic.org.cn:8090'

gem 'thin'
gem 'bootstrap-sass'
gem 'rails', '3.2.16'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql'
gem 'savon', '~> 2.3.0'
#gem 'pg'
gem 'devise'
gem 'warden'
gem 'uuidtools'
#gem 'rubysl'
gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap', '0.2.5'  # for legacy Bootstrap 2 support
gem 'net-ssh', '~> 2.8.0'
gem 'net-scp', '~> 1.2.0'

# Gems used only for assets and not required
# in production environments by default.
group :assets2 do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'd3js-rails'
gem 'acts_as_list'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

# To use rubycas-client
gem 'rubycas-client', '2.3.9'
# To use device_cas_authenticatable
gem 'devise_cas_authenticatable'
gem 'rails-i18n', '~> 3.0.0'
gem 'devise-i18n'

# API framwork
gem 'grape'
gem 'grape-entity'
gem 'api-pagination'

# Lib added by hycloud
gem 'fog', '~>1.37.0'
gem 'eventmachine', '~> 1.2.0.1'
gem 'whenever'